name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ️
        uses: actions/checkout@v2.3.1

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.7.4
          run_install: |
            - recursive: true

      - name: Build
        run: |
          pnpm run build --dir ./alg-lab-1/website
          pnpm run build -dir ./alg-lab-6

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist
